<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>TP Estadística Computacional</title>
  <meta name="description" content="TP Estadística Computacional" />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="TP Estadística Computacional" />
  <meta property="og:type" content="book" />
  
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="TP Estadística Computacional" />
  
  
  

<meta name="author" content="Mateo W. Racca" />


<meta name="date" content="2021-05-04" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  


<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>
<link href="libs/anchor-sections-1.0/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0/anchor-sections.js"></script>


<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">TP Estadística Computacional</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path=""><a href="#tp-estadística-computacional"><i class="fa fa-check"></i><b>1</b> TP Estadística Computacional</a></li>
<li class="chapter" data-level="2" data-path=""><a href="#números-primos"><i class="fa fa-check"></i><b>2</b> Números Primos</a></li>
<li class="chapter" data-level="3" data-path=""><a href="#probabilidad"><i class="fa fa-check"></i><b>3</b> Probabilidad</a></li>
<li class="chapter" data-level="4" data-path=""><a href="#regresiones"><i class="fa fa-check"></i><b>4</b> Regresiones</a><ul>
<li class="chapter" data-level="4.1" data-path=""><a href="#regresión-lineal-simple"><i class="fa fa-check"></i><b>4.1</b> Regresión Lineal Simple</a><ul>
<li class="chapter" data-level="4.1.1" data-path=""><a href="#correlaciones"><i class="fa fa-check"></i><b>4.1.1</b> Correlaciones</a></li>
<li class="chapter" data-level="4.1.2" data-path=""><a href="#regresión-puntos-2014-y-2015"><i class="fa fa-check"></i><b>4.1.2</b> Regresión: puntos 2014 y 2015</a></li>
<li class="chapter" data-level="4.1.3" data-path=""><a href="#regresión-puntos-2015-e-inversión-absoluta"><i class="fa fa-check"></i><b>4.1.3</b> Regresión: puntos 2015 e inversión absoluta</a></li>
<li class="chapter" data-level="4.1.4" data-path=""><a href="#regresión-puntos-2015-y-valor"><i class="fa fa-check"></i><b>4.1.4</b> Regresión: puntos 2015 y valor</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path=""><a href="#residuos-rl"><i class="fa fa-check"></i><b>4.2</b> Residuos RL</a><ul>
<li class="chapter" data-level="4.2.1" data-path=""><a href="#residuos-rl-pts_2014"><i class="fa fa-check"></i><b>4.2.1</b> Residuos RL Pts_2014</a></li>
<li class="chapter" data-level="4.2.2" data-path=""><a href="#residuos-rl-inversión_abs"><i class="fa fa-check"></i><b>4.2.2</b> Residuos RL inversión_abs</a></li>
<li class="chapter" data-level="4.2.3" data-path=""><a href="#residuos-rl-valor"><i class="fa fa-check"></i><b>4.2.3</b> Residuos RL valor</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path=""><a href="#rl-multiple"><i class="fa fa-check"></i><b>4.3</b> RL Multiple</a></li>
<li class="chapter" data-level="4.4" data-path=""><a href="#residuos-rlm"><i class="fa fa-check"></i><b>4.4</b> Residuos RLM</a></li>
<li class="chapter" data-level="4.5" data-path=""><a href="#conclusiones"><i class="fa fa-check"></i><b>4.5</b> Conclusiones</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/raccamateo/tp_estadistica_computacional" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">TP Estadística Computacional</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="header">
<h1 class="title">TP Estadística Computacional</h1>
<p class="author"><em>Mateo W. Racca</em></p>
<p class="date"><em>05/04/21</em></p>
</div>
<div id="tp-estadística-computacional" class="section level1">
<h1><span class="header-section-number">1</span> TP Estadística Computacional</h1>
<p>Este post pretende presentar y desarrollar de manera breve y puntual cuestiones que responden al trabajo práctico de Estadística Computacional del posgrado en Big Data e Inteligencia Geoespacial de FLACSO Argentina (2020). Parte del trabajo se pensó en conjunto con Facundo Benitez Piloni.</p>
</div>
<div id="números-primos" class="section level1">
<h1><span class="header-section-number">2</span> Números Primos</h1>
<p>Por definición, los número primos son aquellos números naturales (enteros, y mayores a 1) que solo son divisibles de manera exacta por dos número naturales: por 1 y por ellos mismos.</p>
<p>Dicho esto, podemos escribir el siguiente algoritmo para encontrar un número primo ubicado en una posición “n”.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1"></a>numero_primo_n &lt;-<span class="st"> </span><span class="cf">function</span>(n)</span>
<span id="cb1-2"><a href="#cb1-2"></a>{</span>
<span id="cb1-3"><a href="#cb1-3"></a>  <span class="co">#como sabemos, los números primos son mayores que 1 (por ende positivos), enteros y solo divisibles por 1 y por si mismos. </span></span>
<span id="cb1-4"><a href="#cb1-4"></a>  <span class="co">#entonces, si el número es menor o igual a 0 configuramos para que el algoritmo nos muestre un mensaje de error</span></span>
<span id="cb1-5"><a href="#cb1-5"></a>  <span class="cf">if</span>(n<span class="op">&lt;=</span><span class="dv">0</span>)</span>
<span id="cb1-6"><a href="#cb1-6"></a>    {</span>
<span id="cb1-7"><a href="#cb1-7"></a>    <span class="kw">return</span>(<span class="st">&quot;Error, solo se aceptan números enteros y mayores a 1&quot;</span>)</span>
<span id="cb1-8"><a href="#cb1-8"></a>    }</span>
<span id="cb1-9"><a href="#cb1-9"></a>  <span class="co">#el primer número primo, por definición arbitraria es el 2 (dos). entonces:</span></span>
<span id="cb1-10"><a href="#cb1-10"></a>  <span class="cf">else</span> <span class="cf">if</span>(n<span class="op">==</span><span class="dv">1</span>)</span>
<span id="cb1-11"><a href="#cb1-11"></a>    {</span>
<span id="cb1-12"><a href="#cb1-12"></a>    <span class="kw">return</span>(<span class="st">&quot;El número primo número 1 es: 2&quot;</span>)</span>
<span id="cb1-13"><a href="#cb1-13"></a>    <span class="co">#el número primo ubicado en la posición 1 siempre va a ser el 2 (dos)</span></span>
<span id="cb1-14"><a href="#cb1-14"></a>    } </span>
<span id="cb1-15"><a href="#cb1-15"></a>  <span class="cf">else</span>{</span>
<span id="cb1-16"><a href="#cb1-16"></a>    <span class="co">#si el número primo que buscamos no se ubica en una posición negativa, ni neutral y es mayor a 1 (uno), el algoritmo nos va a responder que el número que buscamos, en la posición &quot;n&quot; es: (número primo ubicado en la posición &quot;n&quot;)</span></span>
<span id="cb1-17"><a href="#cb1-17"></a>    <span class="kw">print</span>(<span class="kw">paste</span>(<span class="st">&quot;El número primo número&quot;,n, &quot;</span>es<span class="op">:</span><span class="st">&quot;))</span></span>
<span id="cb1-18"><a href="#cb1-18"></a><span class="st">    #vamos a crear un vector para guardar los números entre los que vamos a buscar los números primos ubicados en la posición n</span></span>
<span id="cb1-19"><a href="#cb1-19"></a><span class="st">    disc = c()</span></span>
<span id="cb1-20"><a href="#cb1-20"></a><span class="st">    vec = c()</span></span>
<span id="cb1-21"><a href="#cb1-21"></a><span class="st">    #debemos establecer el limite superior, es decir el número hasta el que el algoritmo va a buscar números primos. </span></span>
<span id="cb1-22"><a href="#cb1-22"></a><span class="st">    # como el número primo 1000 es 7919, vamos a poner como límite 10000 para tener margen de buscar números primos en posiciones mayores pero sin tener un costo computacional demasiado alto sin sentido</span></span>
<span id="cb1-23"><a href="#cb1-23"></a><span class="st">    for(num in seq(3,10000))</span></span>
<span id="cb1-24"><a href="#cb1-24"></a><span class="st">    {</span></span>
<span id="cb1-25"><a href="#cb1-25"></a><span class="st">      #definimos qué números son primos y qué otros no lo son</span></span>
<span id="cb1-26"><a href="#cb1-26"></a><span class="st">      #hay que recordar que nuestro algoritmo va a buscar número mayores a 1, entonces:</span></span>
<span id="cb1-27"><a href="#cb1-27"></a><span class="st">      disc[num-2]= FALSE</span></span>
<span id="cb1-28"><a href="#cb1-28"></a><span class="st">      #paras i en la secuencia desde 2 a num-1:</span></span>
<span id="cb1-29"><a href="#cb1-29"></a><span class="st">      for(i in seq(2,num-1))</span></span>
<span id="cb1-30"><a href="#cb1-30"></a><span class="st">        {</span></span>
<span id="cb1-31"><a href="#cb1-31"></a><span class="st">        if((num%%i)==0)</span></span>
<span id="cb1-32"><a href="#cb1-32"></a><span class="st">          {</span></span>
<span id="cb1-33"><a href="#cb1-33"></a><span class="st">          disc[num-2]=TRUE</span></span>
<span id="cb1-34"><a href="#cb1-34"></a><span class="st">          break</span></span>
<span id="cb1-35"><a href="#cb1-35"></a><span class="st">          }</span></span>
<span id="cb1-36"><a href="#cb1-36"></a><span class="st">        }</span></span>
<span id="cb1-37"><a href="#cb1-37"></a><span class="st">      #los números primos van a ser almacenados en el vector &quot;</span>vec<span class="st">&quot;, cuando no son primos el valor que almacenamos es 0</span></span>
<span id="cb1-38"><a href="#cb1-38"></a><span class="st">      if(disc[num-2]==FALSE)</span></span>
<span id="cb1-39"><a href="#cb1-39"></a><span class="st">        {</span></span>
<span id="cb1-40"><a href="#cb1-40"></a><span class="st">        vec[num-2]=num</span></span>
<span id="cb1-41"><a href="#cb1-41"></a><span class="st">        }</span></span>
<span id="cb1-42"><a href="#cb1-42"></a><span class="st">      else{vec[num-2]=0}</span></span>
<span id="cb1-43"><a href="#cb1-43"></a><span class="st">      }</span></span>
<span id="cb1-44"><a href="#cb1-44"></a><span class="st">    }</span></span>
<span id="cb1-45"><a href="#cb1-45"></a><span class="st"> </span></span>
<span id="cb1-46"><a href="#cb1-46"></a><span class="st">  #creamos un vector nuevo en el que almacenamos los números primos (sin los ceros mencionados arriba que correspondían a números no primos) de manera ordenada de acuerdo a su posición</span></span>
<span id="cb1-47"><a href="#cb1-47"></a><span class="st">  #y hacemos que devuelva el resultado</span></span>
<span id="cb1-48"><a href="#cb1-48"></a><span class="st">  vector_primos &lt;- c()</span></span>
<span id="cb1-49"><a href="#cb1-49"></a><span class="st">  count=1</span></span>
<span id="cb1-50"><a href="#cb1-50"></a><span class="st">  for(k in 1:length(vec))</span></span>
<span id="cb1-51"><a href="#cb1-51"></a><span class="st">    {</span></span>
<span id="cb1-52"><a href="#cb1-52"></a><span class="st">    if((vec[k])!=0)</span></span>
<span id="cb1-53"><a href="#cb1-53"></a><span class="st">      {</span></span>
<span id="cb1-54"><a href="#cb1-54"></a><span class="st">      vector_primos[count] &lt;- vec[k]  </span></span>
<span id="cb1-55"><a href="#cb1-55"></a><span class="st">      count = count+1</span></span>
<span id="cb1-56"><a href="#cb1-56"></a><span class="st">      }</span></span>
<span id="cb1-57"><a href="#cb1-57"></a><span class="st">    }</span></span>
<span id="cb1-58"><a href="#cb1-58"></a><span class="st">  return(vector_primos[n-1])</span></span>
<span id="cb1-59"><a href="#cb1-59"></a><span class="st">  }</span></span></code></pre></div>
<p>Ahora, como la consigna del trabajo práctico pide averiguar el número primo ubicado en la posición número 1000, lo que debemos hacer es usar la función que creamos para encontrar números primos y pedirle que busque el número ubicado en la posición 1000:</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1"></a><span class="kw">numero_primo_n</span>(<span class="dv">1000</span>)</span></code></pre></div>
<pre><code>## [1] &quot;El número primo número 1000 es:&quot;</code></pre>
<pre><code>## [1] 7919</code></pre>
<p>En caso de que necesitemos buscar otro número primo ubicado en la posición “n”, debemos ejecutar la función <em>numero_primo_numero(n)</em>.
La limitación de esta función es que busca número primos en el rango 2-10000 y si buscamos un número ubicado en una posición demasiado alta quizás debamos modificarlo.</p>
</div>
<div id="probabilidad" class="section level1">
<h1><span class="header-section-number">3</span> Probabilidad</h1>
<p>El apartado de probabilidad consiste en averiguar cual es la probabilidad de obtener una generala para cinco dados al cabo de 3 intentos. En cada intento se tiran 5 dados, y cada uno de esos dados tiene 6 caras. Entonces, la probabilidad de que en un intento salgan 5 número iguales se calcula de la siguiente manera:</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1"></a>probabilidad =<span class="st"> </span><span class="dv">1</span><span class="op">*</span>(<span class="dv">1</span><span class="op">/</span><span class="dv">6</span>)<span class="op">*</span>(<span class="dv">1</span><span class="op">/</span><span class="dv">6</span>)<span class="op">*</span>(<span class="dv">1</span><span class="op">/</span><span class="dv">6</span>)<span class="op">*</span>(<span class="dv">1</span><span class="op">/</span><span class="dv">6</span>)</span>
<span id="cb5-2"><a href="#cb5-2"></a></span>
<span id="cb5-3"><a href="#cb5-3"></a><span class="co">#usamos la función round para especificar 5 decimales</span></span>
<span id="cb5-4"><a href="#cb5-4"></a>probabilidad &lt;-<span class="st"> </span><span class="kw">round</span>(probabilidad, <span class="dt">digits =</span> <span class="dv">5</span>)</span>
<span id="cb5-5"><a href="#cb5-5"></a></span>
<span id="cb5-6"><a href="#cb5-6"></a><span class="co">#usamos print para que nos devuelva el resultado de probabilidad con algo de texto</span></span>
<span id="cb5-7"><a href="#cb5-7"></a><span class="kw">print</span>(<span class="kw">paste</span>(<span class="st">&quot;La probabilidad de obtener una generala es:&quot;</span>, probabilidad))</span></code></pre></div>
<pre><code>## [1] &quot;La probabilidad de obtener una generala es: 0.00077&quot;</code></pre>
<p>¿Cómo se calculó la probabilidad de un lanzamiento?</p>
<p>Ya que el primer dado puede tomar cualquier valor, la probabilidad es 1. Ahora, en los otros 4 dados, la probabilidad de que sean igual al primero es de 1/6, por lo que la probabilidad es 1 por 1/6, por 1/6, por 1/6, por 1/6, por 1/6.</p>
<p>Si queremos conocer la probabilidad en porcentaje:</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1"></a>probabilidad_porcentual =<span class="st"> </span>probabilidad<span class="op">*</span><span class="dv">100</span></span>
<span id="cb7-2"><a href="#cb7-2"></a></span>
<span id="cb7-3"><a href="#cb7-3"></a><span class="co">#usamos la función round para especificar 3 decimales</span></span>
<span id="cb7-4"><a href="#cb7-4"></a>probabilidad &lt;-<span class="st"> </span><span class="kw">round</span>(probabilidad, <span class="dt">digits =</span> <span class="dv">3</span>)</span>
<span id="cb7-5"><a href="#cb7-5"></a></span>
<span id="cb7-6"><a href="#cb7-6"></a><span class="co">#usamos print para que nos devuelva el resultado de probabilidad con algo de texto</span></span>
<span id="cb7-7"><a href="#cb7-7"></a><span class="kw">print</span>(<span class="kw">paste</span>(<span class="st">&quot;El porcentaje de probabilidad de obtener una generala es:&quot;</span>, probabilidad_porcentual))</span></code></pre></div>
<pre><code>## [1] &quot;El porcentaje de probabilidad de obtener una generala es: 0.077&quot;</code></pre>
</div>
<div id="regresiones" class="section level1">
<h1><span class="header-section-number">4</span> Regresiones</h1>
<p>El apartado de regresiones tiene como objetivo usar una regresión lineal para explicar la variable <em>Pts</em> (puntos) a partir de las variables <em>Pts_2012_13</em>, <em>Pts_2013_14</em>, <em>Pts_2014</em>, <em>inversion_abs</em> (inversión absoluta), <em>inversion_relativa</em> (inversión relativa), <em>valor</em> (valor en millones de euros), <em>libertadores</em> (si participó en el 2015 en la Copa Libertadores), <em>sudamericana</em> (si participó en el 2015 en la Copa Sudamericana) y <em>ascenso</em> (si ascendió).</p>
<p>Ahora, empecemos con los datos:</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1"></a><span class="co">#cargamos el .csv</span></span>
<span id="cb9-2"><a href="#cb9-2"></a>datos_generales &lt;-<span class="st"> </span><span class="kw">read.csv2</span>(<span class="st">&quot;datos_2015.csv&quot;</span>, </span>
<span id="cb9-3"><a href="#cb9-3"></a>                             <span class="dt">sep =</span> <span class="st">&quot;;&quot;</span>,</span>
<span id="cb9-4"><a href="#cb9-4"></a>                             <span class="dt">encoding =</span> <span class="st">&quot;UTF-8&quot;</span>)</span>
<span id="cb9-5"><a href="#cb9-5"></a></span>
<span id="cb9-6"><a href="#cb9-6"></a><span class="co">#usamos str para ver con qué variables (y de qué tipo) nos encontramos</span></span>
<span id="cb9-7"><a href="#cb9-7"></a><span class="kw">str</span>(datos_generales)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    30 obs. of  49 variables:
##  $ club              : chr  &quot;Quilmes&quot; &quot;Olimpo&quot; &quot;Banfield&quot; &quot;Godoy Cruz&quot; ...
##  $ Pts_2012_13       : int  50 0 0 0 0 49 0 43 59 74 ...
##  $ Pts_2013_14       : int  45 50 0 0 54 56 57 49 49 56 ...
##  $ Pts_2014          : int  12 19 20 20 21 21 24 25 25 25 ...
##  $ inversion_abs     : chr  &quot;6.33&quot; &quot;2.25&quot; &quot;7.55&quot; &quot;3.4&quot; ...
##  $ inversion_relativa: chr  &quot;0.650965567&quot; &quot;0.25489225&quot; &quot;0.590507433&quot; &quot;0.301022445&quot; ...
##  $ valor             : chr  &quot;13.23&quot; &quot;10&quot; &quot;16.93&quot; &quot;13.08&quot; ...
##  $ libertadores      : int  0 0 0 0 0 0 0 0 1 0 ...
##  $ sudamericana      : int  0 0 0 0 0 0 0 0 0 0 ...
##  $ ascenso           : int  0 0 0 0 0 0 0 0 0 1 ...
##  $ Pos               : int  11 18 8 22 3 21 12 29 7 15 ...
##  $ Pts               : int  45 36 50 32 59 32 44 23 51 40 ...
##  $ PJ                : int  30 30 30 30 30 30 30 30 30 30 ...
##  $ PG                : int  13 8 14 8 16 8 12 4 14 11 ...
##  $ PE                : int  6 12 8 8 11 8 8 11 9 7 ...
##  $ PP                : int  11 10 8 14 3 14 10 15 7 12 ...
##  $ GF                : int  38 23 38 32 47 27 41 29 34 37 ...
##  $ GC                : int  37 26 32 40 26 31 38 51 28 40 ...
##  $ Dif               : int  1 -3 6 -8 21 -4 3 -22 6 -3 ...
##  $ Pos_Fecha_1       : int  19 25 19 14 8 8 19 27 8 27 ...
##  $ Pos_Fecha_2       : int  18 25 12 18 4 14 20 30 4 29 ...
##  $ Pos_Fecha_3       : int  24 29 12 14 3 18 27 30 2 27 ...
##  $ Pos_Fecha_4       : int  23 29 18 8 1 15 25 30 4 25 ...
##  $ Pos_Fecha_5       : int  19 29 13 16 1 18 20 30 5 21 ...
##  $ Pos_Fecha_6       : int  20 25 9 19 1 18 24 30 11 21 ...
##  $ Pos_Fecha_7       : int  22 26 5 18 3 17 25 30 14 21 ...
##  $ Pos_Fecha_8       : int  20 27 6 21 4 19 25 28 15 17 ...
##  $ Pos_Fecha_9       : int  22 28 7 23 4 18 19 29 16 20 ...
##  $ Pos_Fecha_10      : int  23 30 9 24 4 21 18 29 20 11 ...
##  $ Pos_Fecha_11      : int  21 28 10 22 5 24 17 26 18 8 ...
##  $ Pos_Fecha_12      : int  20 25 9 21 3 24 18 26 17 11 ...
##  $ Pos_Fecha_13      : int  23 25 10 19 3 24 15 28 13 9 ...
##  $ Pos_Fecha_14      : int  23 26 10 22 5 25 13 28 15 11 ...
##  $ Pos_Fecha_15      : int  23 28 12 22 5 27 8 26 10 14 ...
##  $ Pos_Fecha_16      : int  23 28 10 18 4 26 8 27 12 15 ...
##  $ Pos_Fecha_17      : int  23 26 14 19 6 24 7 28 11 16 ...
##  $ Pos_Fecha_18      : int  21 26 13 17 4 22 7 28 12 16 ...
##  $ Pos_Fecha_19      : int  18 22 12 19 4 24 8 27 11 17 ...
##  $ Pos_Fecha_20      : int  15 22 9 19 6 25 8 27 11 18 ...
##  $ Pos_Fecha_21      : int  15 24 9 21 4 22 8 27 11 18 ...
##  $ Pos_Fecha_22      : int  15 22 8 23 3 24 9 27 10 17 ...
##  $ Pos_Fecha_23      : int  14 23 9 25 3 21 12 27 8 19 ...
##  $ Pos_Fecha_24      : int  13 21 7 23 3 19 12 27 10 18 ...
##  $ Pos_Fecha_25      : int  13 22 6 25 3 20 12 27 8 17 ...
##  $ Pos_Fecha_26      : int  11 20 8 25 3 22 14 28 10 18 ...
##  $ Pos_Fecha_27      : int  11 20 9 23 3 19 14 28 8 16 ...
##  $ Pos_Fecha_28      : int  11 18 10 21 2 20 12 29 6 16 ...
##  $ Pos_Fecha_29      : int  11 17 9 22 3 20 12 29 8 15 ...
##  $ Pos_Fecha_30      : int  11 18 8 22 3 21 12 29 7 15 ...</code></pre>
<p>Como en el dataset original hay 49 variables y las mencionadas en la consigna (y necesarias para este ejercicio) son 10, vamos a seleccionar variables.</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1"></a><span class="co">#seleccionamos las variables necesarias</span></span>
<span id="cb11-2"><a href="#cb11-2"></a>datos &lt;-<span class="st"> </span>datos_generales <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb11-3"><a href="#cb11-3"></a><span class="st">  </span><span class="kw">select</span>(Pts_<span class="dv">2012</span>_<span class="dv">13</span><span class="op">:</span>ascenso, Pts)</span>
<span id="cb11-4"><a href="#cb11-4"></a><span class="co">#repasamos para ver qué variables seleccionamos</span></span>
<span id="cb11-5"><a href="#cb11-5"></a><span class="kw">str</span>(datos) </span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    30 obs. of  10 variables:
##  $ Pts_2012_13       : int  50 0 0 0 0 49 0 43 59 74 ...
##  $ Pts_2013_14       : int  45 50 0 0 54 56 57 49 49 56 ...
##  $ Pts_2014          : int  12 19 20 20 21 21 24 25 25 25 ...
##  $ inversion_abs     : chr  &quot;6.33&quot; &quot;2.25&quot; &quot;7.55&quot; &quot;3.4&quot; ...
##  $ inversion_relativa: chr  &quot;0.650965567&quot; &quot;0.25489225&quot; &quot;0.590507433&quot; &quot;0.301022445&quot; ...
##  $ valor             : chr  &quot;13.23&quot; &quot;10&quot; &quot;16.93&quot; &quot;13.08&quot; ...
##  $ libertadores      : int  0 0 0 0 0 0 0 0 1 0 ...
##  $ sudamericana      : int  0 0 0 0 0 0 0 0 0 0 ...
##  $ ascenso           : int  0 0 0 0 0 0 0 0 0 1 ...
##  $ Pts               : int  45 36 50 32 59 32 44 23 51 40 ...</code></pre>
<p>Antes de poder trabajar con las regresiones, necesitamos cambiar algunos tipos de variables a numéricas y otras a lógicas:</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1"></a><span class="co">#tomamos las variables ubicadas en las columnas 1-6 y 10 y las transformamos en numéricas</span></span>
<span id="cb13-2"><a href="#cb13-2"></a>datos[,<span class="dv">1</span><span class="op">:</span><span class="dv">6</span>] &lt;-<span class="st"> </span><span class="kw">sapply</span>(datos[,<span class="dv">1</span><span class="op">:</span><span class="dv">6</span>],as.numeric)</span>
<span id="cb13-3"><a href="#cb13-3"></a><span class="co">#tomamos las variables ubicadas en la columna 10 y la transformamos en numérica</span></span>
<span id="cb13-4"><a href="#cb13-4"></a>datos[,<span class="dv">10</span>] &lt;-<span class="st"> </span><span class="kw">sapply</span>(datos[,<span class="dv">10</span>],as.numeric)</span>
<span id="cb13-5"><a href="#cb13-5"></a><span class="co">#tomamos las variables ubicadas en las columnas 7-9 y las transformamos en numéricas</span></span>
<span id="cb13-6"><a href="#cb13-6"></a>datos[,<span class="dv">7</span><span class="op">:</span><span class="dv">9</span>] &lt;-<span class="st"> </span><span class="kw">sapply</span>(datos[,<span class="dv">7</span><span class="op">:</span><span class="dv">9</span>],as.logical)</span>
<span id="cb13-7"><a href="#cb13-7"></a><span class="co">#repasamos para ver qué variables seleccionamos</span></span>
<span id="cb13-8"><a href="#cb13-8"></a><span class="kw">str</span>(datos) </span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    30 obs. of  10 variables:
##  $ Pts_2012_13       : num  50 0 0 0 0 49 0 43 59 74 ...
##  $ Pts_2013_14       : num  45 50 0 0 54 56 57 49 49 56 ...
##  $ Pts_2014          : num  12 19 20 20 21 21 24 25 25 25 ...
##  $ inversion_abs     : num  6.33 2.25 7.55 3.4 10.83 ...
##  $ inversion_relativa: num  0.651 0.255 0.591 0.301 1.088 ...
##  $ valor             : num  13.2 10 16.9 13.1 16.3 ...
##  $ libertadores      : logi  FALSE FALSE FALSE FALSE FALSE FALSE ...
##  $ sudamericana      : logi  FALSE FALSE FALSE FALSE FALSE FALSE ...
##  $ ascenso           : logi  FALSE FALSE FALSE FALSE FALSE FALSE ...
##  $ Pts               : num  45 36 50 32 59 32 44 23 51 40 ...</code></pre>
<div id="regresión-lineal-simple" class="section level2">
<h2><span class="header-section-number">4.1</span> Regresión Lineal Simple</h2>
<p>En estadística, la regresión lineal es un modelo matemático usado para aproximar la relación de dependencia entre una variable dependiente <em>y</em> con la variable independiente <em>x</em>. Se puede representar con la fórmula:</p>
<p><strong><em>y = a + b </em> x</strong>*</p>
<p>A cada punto en <em>x</em> le corresponde un valor en <em>y</em>. El valor de <em>y</em> es resultado de multiplicar <em>x</em> por la pendiente <em>b</em>, y de sumar la ordenada al origen <em>a</em>. Se le llama “ordenada al origen” o “intersección” ya que es el valor donde la recta intersecta con el eje <em>y</em> cuando <em>x</em> vale 0.</p>
<p>En una regresión lineal, el “modelo” que creamos es una línea que minimiza la distancia al cuadrado de todos los puntos, lo que nos permite conocer cuánto varía la variable dependiente <em>y</em> por cada cambio de unidad en la variable independiente <em>x</em> y también predecir o estimar valores.</p>
<p>Vamos a recordar los supuestos del modelo de regresión lineal:
* <em>Linealidad</em>
* <em>Independencia</em>
* <em>Normalidad</em>
* <em>Homocedasticidad</em></p>
<p>En este dataset la variable dependiente <em>y</em> es la variable <em>Pts</em>, que representa la cantidad de puntos alcanzados por los distintos clubes que compitieron en la primera división del fútbol argentino durante el campeonato 2015.</p>
<p>Vamos a ver esto en un histograma:</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1"></a><span class="kw">hist</span>(datos<span class="op">$</span>Pts, <span class="dt">main =</span> <span class="st">&quot;Histograma: puntos obtenidos en el torneo 2015&quot;</span>, </span>
<span id="cb15-2"><a href="#cb15-2"></a>     <span class="dt">xlab =</span> <span class="st">&quot;Puntos&quot;</span>, <span class="dt">ylab =</span> <span class="st">&quot;Frecuencia&quot;</span>)</span></code></pre></div>
<p><img src="index_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<p>La distribución de puntos obtenidos por los equipos en el torneo 2015 va desde los 14 hasta los 64.</p>
<div id="correlaciones" class="section level3">
<h3><span class="header-section-number">4.1.1</span> Correlaciones</h3>
<p>Vamos a averiguar el grado de correlación entre las variables. Antes, vamos a recordar el criterio de evaluación del grado de correlación:</p>
<ul>
<li><em>de 0.7 a 1</em>: fuerte a total</li>
<li><em>de 0.5 a 0.7</em>: moderada a fuerte</li>
<li><em>de 0.3 a 0.5</em>: débil a moderada</li>
<li><em>menor a 0.3</em>: nula a débil</li>
</ul>
<p>Ahora, vamos a calcular la correlación de nuestra variable dependiente <em>y</em> (Pts) con el resto de las variables.</p>
</div>
<div id="regresión-puntos-2014-y-2015" class="section level3">
<h3><span class="header-section-number">4.1.2</span> Regresión: puntos 2014 y 2015</h3>
<p>Vamos a calcular una regresión con la variable dependiente <em>Pts</em> y la independiente <em>Pts_2014</em>. Antes, vamos a ver nuestros datos en un gráfico de puntos:</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1"></a><span class="kw">ggplot</span>(datos) <span class="op">+</span></span>
<span id="cb16-2"><a href="#cb16-2"></a><span class="st">  </span><span class="kw">geom_point</span>(<span class="kw">aes</span>(<span class="dt">x =</span> Pts_<span class="dv">2014</span>, <span class="dt">y =</span> Pts)) <span class="op">+</span></span>
<span id="cb16-3"><a href="#cb16-3"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&#39;Puntos en 2014 y 2015&#39;</span>) <span class="op">+</span></span>
<span id="cb16-4"><a href="#cb16-4"></a><span class="st">  </span><span class="kw">theme_minimal</span>()</span></code></pre></div>
<p><img src="index_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<p>Ahora calculamos la regresión:</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1"></a>lr_Pts_<span class="dv">2014</span>&lt;-<span class="st"> </span><span class="kw">lm</span>(Pts<span class="op">~</span><span class="st"> </span>Pts_<span class="dv">2014</span>, datos)</span>
<span id="cb17-2"><a href="#cb17-2"></a></span>
<span id="cb17-3"><a href="#cb17-3"></a>lr_Pts_<span class="dv">2014</span></span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Pts ~ Pts_2014, data = datos)
## 
## Coefficients:
## (Intercept)     Pts_2014  
##     31.5541       0.5017</code></pre>
<p>Y vemos las estadísticas de resumen:</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1"></a><span class="kw">summary</span>(lr_Pts_<span class="dv">2014</span>)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Pts ~ Pts_2014, data = datos)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -21.0959  -4.8383   0.9041   6.6508  16.9108 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  31.5541     3.0209   10.45 3.65e-11 ***
## Pts_2014      0.5017     0.1363    3.68 0.000985 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 10.15 on 28 degrees of freedom
## Multiple R-squared:  0.326,  Adjusted R-squared:  0.3019 
## F-statistic: 13.54 on 1 and 28 DF,  p-value: 0.0009849</code></pre>
<p><em>Estimate</em> nos devuelve el valor estimado de la ordenada al origen y la pendiente.</p>
<p>Nuestro modelo es significativo porque:
* los coeficientes de regresión son 31.5541 y 0.5017.
* el p-value (nivel de significación del estudio) es 0.0009849, lo que nos permite rechazar la hipótesis nula. En este caso, la <em>H0</em> plantea que la variable no es estadísticamente significativa para predecir el valor, y en consecuencia nuestra variable tiene significancia.</p>
<p>El <em>R cuadrado</em> describe la proporción de variabilidad de la variable dependiente (<em>y</em>) del modelo y relativa a la variabilidad total. Mide el nivel de ajuste e indica qué porcentaje de la variabilidad de <em>y</em> es explicado por <em>x</em>.</p>
<p>En la regresión lineal entre <em>Pts_2014</em> y <em>Pts</em>, el valor de R cuadrado es <em>0.3019</em>. ¿Qué significa esto? Que el 30.2% de la variabilidad de los puntos de 2015 (la variable <em>Pts</em>) se explica por los puntos de 2014 (<em>Pts_2014</em>). El resto de la variabilidad se debe al azar o a otras variables no incluidas en este modelo.</p>
<p>Vamos a ver el gráfico de puntos anterior pero ahora con la recta de regresión:</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1"></a><span class="kw">ggplot</span>(datos) <span class="op">+</span></span>
<span id="cb21-2"><a href="#cb21-2"></a><span class="st">  </span><span class="kw">geom_point</span>(<span class="kw">aes</span>(<span class="dt">x =</span> Pts_<span class="dv">2014</span>, <span class="dt">y =</span> Pts)) <span class="op">+</span></span>
<span id="cb21-3"><a href="#cb21-3"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&#39;Regresión: puntos 2014 y 2015&#39;</span>) <span class="op">+</span></span>
<span id="cb21-4"><a href="#cb21-4"></a><span class="st">  </span><span class="kw">geom_abline</span>(<span class="kw">aes</span>(<span class="dt">intercept =</span> <span class="fl">31.5541</span>, <span class="dt">slope =</span>  <span class="fl">0.5017</span>), <span class="dt">color =</span> <span class="st">&#39;red&#39;</span>) <span class="op">+</span></span>
<span id="cb21-5"><a href="#cb21-5"></a><span class="st">  </span><span class="kw">xlim</span>(<span class="kw">c</span>(<span class="dv">0</span>,<span class="dv">50</span>)) <span class="op">+</span></span>
<span id="cb21-6"><a href="#cb21-6"></a><span class="st">  </span><span class="kw">ylim</span>(<span class="dv">0</span>,<span class="dv">70</span>) <span class="op">+</span></span>
<span id="cb21-7"><a href="#cb21-7"></a><span class="st">  </span><span class="kw">theme_minimal</span>()</span></code></pre></div>
<p><img src="index_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
<p>El gráfico muestra una correlación positiva entre las variables <em>Pts</em> y <em>Pts_2014</em>. Hay equipos que no tuvieron puntos en un torneo y sí en otro, y esto se debe a que no han competido. Algunos equipos que no participaron en 2014 obtuvieron entre 20 y 40 en 2015 mientras que gran parte de los equipos que alcanzaron entre 20 y 40 puntos en 2014 tuvieron un desempeño similar (a veces incluso mejor) en 2015.</p>
<p>Es importante destacar que el modelo tiene cierto ruido, y que los puntos suelen tomar valores distanciados de la recta de regresión por lo que no está ajustado de manera ideal.</p>
</div>
<div id="regresión-puntos-2015-e-inversión-absoluta" class="section level3">
<h3><span class="header-section-number">4.1.3</span> Regresión: puntos 2015 e inversión absoluta</h3>
<p>Vamos a trabajar con una regresión lineal simple entre la variable <em>Pts</em> e <em>inversion_abs</em>. En esta y en la próxima regresión vamos a ir directo a los modelos y a los gráficos con sus rectas de regresión.</p>
<p>Vamos a calcular la regresión lineal:</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1"></a>lr_inversion_absoluta &lt;-<span class="st">  </span><span class="kw">lm</span>(Pts <span class="op">~</span><span class="st"> </span>inversion_abs,</span>
<span id="cb22-2"><a href="#cb22-2"></a>               datos)</span>
<span id="cb22-3"><a href="#cb22-3"></a></span>
<span id="cb22-4"><a href="#cb22-4"></a>lr_inversion_absoluta</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Pts ~ inversion_abs, data = datos)
## 
## Coefficients:
##   (Intercept)  inversion_abs  
##        36.142          1.744</code></pre>
<p>Vemos las estadísticas de resumen:</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1"></a><span class="kw">summary</span>(lr_inversion_absoluta)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Pts ~ inversion_abs, data = datos)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -22.142  -7.132  -2.467   4.501  25.915 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)    36.1424     2.2854  15.815 1.73e-15 ***
## inversion_abs   1.7440     0.5228   3.336  0.00241 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 10.46 on 28 degrees of freedom
## Multiple R-squared:  0.2844, Adjusted R-squared:  0.2589 
## F-statistic: 11.13 on 1 and 28 DF,  p-value: 0.002407</code></pre>
<p>Existe relación positiva entre las variables <em>Pts</em> e <em>inversion_abs</em>, y el modelo es significativo porque:
* el p-value es 0.002407, por lo que podemos aceptarlo ya que como explicamos arriba rechaza la hipótesis nula.
* el R cuadrado es de 0.2589, lo que significa que el 25.9% de la variabilidad de los puntos de 2015 (<em>Pts</em>) se explica por la inversión (<em>inversión_abs</em>). El resto de la variabilidad se debe al azar o a otras variables no incluidas en este modelo.</p>
<p>Vamos a ver el gráfico de puntos anterior pero ahora con la recta de regresión:</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1"></a><span class="kw">ggplot</span>(datos) <span class="op">+</span></span>
<span id="cb26-2"><a href="#cb26-2"></a><span class="st">  </span><span class="kw">geom_point</span>(<span class="kw">aes</span>(<span class="dt">x =</span> inversion_abs, <span class="dt">y =</span> Pts)) <span class="op">+</span></span>
<span id="cb26-3"><a href="#cb26-3"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&#39;Regresión: puntos 2015 e inversión absoluta&#39;</span>) <span class="op">+</span></span>
<span id="cb26-4"><a href="#cb26-4"></a><span class="st">  </span><span class="kw">geom_abline</span>(<span class="kw">aes</span>(<span class="dt">intercept =</span> <span class="fl">36.1424</span>, <span class="dt">slope =</span> <span class="fl">1.744</span>), <span class="dt">color =</span> <span class="st">&#39;red&#39;</span>) <span class="op">+</span></span>
<span id="cb26-5"><a href="#cb26-5"></a><span class="st">  </span><span class="kw">xlim</span>(<span class="kw">c</span>(<span class="op">-</span><span class="dv">4</span>,<span class="dv">12</span>)) <span class="op">+</span></span>
<span id="cb26-6"><a href="#cb26-6"></a><span class="st">  </span><span class="kw">ylim</span>(<span class="dv">0</span>,<span class="dv">70</span>) <span class="op">+</span></span>
<span id="cb26-7"><a href="#cb26-7"></a><span class="st">  </span><span class="kw">theme_minimal</span>()</span></code></pre></div>
<p><img src="index_files/figure-html/unnamed-chunk-15-1.png" width="672" /></p>
<p>Del gráfico podemos concluir que los clubes cuya inversión absoluta fue mayor a cero y de hasta 1,75 millones alcanzaron puntajes ubicados entre los 25 los 40 puntos aproximadamente. Hay dos excepciones, que podrían ser catalogadas como outliers: una con menos de 20 puntos y otra que supera los 60 puntos.</p>
<p>Por otro lado, todos los equipos cuya inversión absoluta supera los 2 millones de dolares alcanzaron un puntaje mayor a 30 puntos. Tal como en el caso anterior, el modelo no se ajusta de manera deseable.</p>
</div>
<div id="regresión-puntos-2015-y-valor" class="section level3">
<h3><span class="header-section-number">4.1.4</span> Regresión: puntos 2015 y valor</h3>
<p>La última regresión lineal implica las variables <em>Pts</em> y <em>valor</em>. Calculamos la regresión:</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1"></a>lr_valor &lt;-<span class="st">  </span><span class="kw">lm</span>(Pts <span class="op">~</span><span class="st"> </span>valor,</span>
<span id="cb27-2"><a href="#cb27-2"></a>               datos)</span>
<span id="cb27-3"><a href="#cb27-3"></a></span>
<span id="cb27-4"><a href="#cb27-4"></a>lr_valor</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Pts ~ valor, data = datos)
## 
## Coefficients:
## (Intercept)        valor  
##     29.6578       0.7111</code></pre>
<p>Ahora vamos a ver las estadísticas de resumen:</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1"></a><span class="kw">summary</span>(lr_valor)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Pts ~ valor, data = datos)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -18.8081  -6.8428  -0.7274   6.7124  17.7294 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  29.6578     3.1246   9.492 3.01e-10 ***
## valor         0.7111     0.1713   4.152 0.000279 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 9.725 on 28 degrees of freedom
## Multiple R-squared:  0.3811, Adjusted R-squared:  0.359 
## F-statistic: 17.24 on 1 and 28 DF,  p-value: 0.0002791</code></pre>
<p>Como se pudo ver al momento de calcular la correlación, la correlación entre estas variables fue la más alta con un valor de <em>0,61</em>.</p>
<p>Existe relación positiva entre las variables <em>Pts</em> y <em>valor</em>, y el modelo es significativo porque:
* el p-value es 0.0002791, por lo que podemos aceptarlo.
* el R cuadrado es de 0.359, lo que significa que el 35.9% de la variabilidad de los puntos de 2015 (<em>Pts</em>) se explica por el valor en millones de euros (<em>valor</em>). El resto de la variabilidad se debe al azar o a otras variables no incluidas en este modelo.</p>
<p>Graficamos:</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1"></a><span class="kw">ggplot</span>(datos) <span class="op">+</span></span>
<span id="cb31-2"><a href="#cb31-2"></a><span class="st">  </span><span class="kw">geom_point</span>(<span class="kw">aes</span>(<span class="dt">x =</span> valor, <span class="dt">y =</span> Pts)) <span class="op">+</span></span>
<span id="cb31-3"><a href="#cb31-3"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&#39;Regresión: puntos 2015 y valor&#39;</span>) <span class="op">+</span></span>
<span id="cb31-4"><a href="#cb31-4"></a><span class="st">  </span><span class="kw">geom_abline</span>(<span class="kw">aes</span>(<span class="dt">intercept =</span>   <span class="fl">29.6578</span> , <span class="dt">slope=</span> <span class="fl">0.7111</span>), <span class="dt">color =</span> <span class="st">&#39;red&#39;</span>) <span class="op">+</span></span>
<span id="cb31-5"><a href="#cb31-5"></a><span class="st">  </span><span class="kw">xlim</span>(<span class="kw">c</span>(<span class="dv">0</span>,<span class="dv">45</span>)) <span class="op">+</span></span>
<span id="cb31-6"><a href="#cb31-6"></a><span class="st">  </span><span class="kw">ylim</span>(<span class="dv">0</span>,<span class="dv">70</span>) <span class="op">+</span></span>
<span id="cb31-7"><a href="#cb31-7"></a><span class="st">  </span><span class="kw">theme_minimal</span>()</span></code></pre></div>
<p><img src="index_files/figure-html/unnamed-chunk-18-1.png" width="672" /></p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1"></a><span class="kw">summary</span>(datos<span class="op">$</span>valor)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   3.380   7.312  13.155  15.012  17.973  43.400</code></pre>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1"></a><span class="kw">summary</span>(datos<span class="op">$</span>Pts)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   14.00   30.50   40.00   40.33   49.75   64.00</code></pre>
<p>La variable <em>valor</em> (en millones de euros) toma valores en un rango de entre 14 y 64 puntos (<em>Pts</em>).</p>
</div>
</div>
<div id="residuos-rl" class="section level2">
<h2><span class="header-section-number">4.2</span> Residuos RL</h2>
<p>Los residuos son las diferencias encontradas entre el valor que predice un modelo para una variable y el valor observado en la práctia. Representan el desvío de cada observación respecto al valor “esperado” por nuestro modelo.</p>
<p>Cuando los desvíos son pequeños (y en consecuencia los residuos lo son), decimos que el modelo se ajusta bien a los datos observados. Cuando los residuos son grandes ocurre lo contrario, y quizás deberíamos buscar otra forma de describir y/o modelar la relación entre las variables ya que este modelo no es óptimo.</p>
<p>Para calcular los residuos vamos a usar la función <em>residuals()</em> y para verificar si el modelo cumple los supuestos vamos a graficar con la función <em>plot()</em>.</p>
<div id="residuos-rl-pts_2014" class="section level3">
<h3><span class="header-section-number">4.2.1</span> Residuos RL Pts_2014</h3>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1"></a>residuos_Pts_<span class="dv">2014</span>&lt;-<span class="st"> </span><span class="kw">residuals</span>(lr_Pts_<span class="dv">2014</span>)</span>
<span id="cb36-2"><a href="#cb36-2"></a></span>
<span id="cb36-3"><a href="#cb36-3"></a>residuos_Pts_<span class="dv">2014</span></span></code></pre></div>
<pre><code>##           1           2           3           4           5           6 
##   7.4258474  -5.0858372   8.4124936  -9.5875064  16.9108244 -10.0891756 
##           7           8           9          10          11          12 
##   0.4058167 -21.0958525   6.9041475  -4.0958525 -15.0958525 -17.5975217 
##          13          14          15          16          17          18 
##   1.4024783  16.4024783   3.8941322  16.8941322   5.8907937  -7.1125447 
##          19          20          21          22          23          24 
##  -2.1192216   4.8774399   9.4458781   8.4458781   5.4458781   2.4458781 
##          25          26          27          28          29          30 
##   1.4458781  -1.5541219  -1.5541219  -1.5541219  -2.5541219 -17.5541219</code></pre>
<p>Como podemos ver, la función <em>residuals()</em> nos devuelve el residuo para cada observación. Ahora vamos a graficar estos resultados:</p>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1"></a><span class="kw">ggplot</span>()<span class="op">+</span></span>
<span id="cb38-2"><a href="#cb38-2"></a><span class="st">  </span><span class="kw">geom_point</span>(<span class="kw">aes</span>(<span class="dt">x=</span>datos<span class="op">$</span>Pts_<span class="dv">2014</span>, <span class="dt">y=</span>residuos_Pts_<span class="dv">2014</span>))<span class="op">+</span></span>
<span id="cb38-3"><a href="#cb38-3"></a><span class="st">  </span><span class="kw">geom_hline</span>(<span class="dt">yintercept =</span> <span class="dv">0</span>, <span class="dt">col =</span> <span class="st">&#39;red&#39;</span>)<span class="op">+</span></span>
<span id="cb38-4"><a href="#cb38-4"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">title=</span><span class="st">&quot;Residuos RL: Pts y Pts_2014&quot;</span>,</span>
<span id="cb38-5"><a href="#cb38-5"></a>       <span class="dt">y=</span><span class="st">&quot;residuos&quot;</span>,</span>
<span id="cb38-6"><a href="#cb38-6"></a>       <span class="dt">x=</span><span class="st">&quot;Puntos 2014&quot;</span>) <span class="op">+</span></span>
<span id="cb38-7"><a href="#cb38-7"></a><span class="st">  </span><span class="kw">theme_minimal</span>() </span></code></pre></div>
<p><img src="index_files/figure-html/unnamed-chunk-20-1.png" width="672" /></p>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1"></a><span class="kw">summary</span>(residuos_Pts_<span class="dv">2014</span>)</span></code></pre></div>
<pre><code>##     Min.  1st Qu.   Median     Mean  3rd Qu.     Max. 
## -21.0959  -4.8383   0.9041   0.0000   6.6508  16.9108</code></pre>
<p>Del resumen de los residuos y la visualización podemos decir que hay cierto equilibrio entre los puntos ubicados debajo y encima del cero. Hay que destacar que también encontramos una distribución desigual de residuos a lo largo del eje <em>x</em> ya que varios residuos se concentran en 0. ¿Por qué pasa esto? Porque son equipos que no obtuvieron puntos en el torneo. La distribución parece normalizarse para el resto de los valores de <em>x</em>.</p>
<p>Ahora, vamos a ver otros gráficos que nos van a ayudar a entender mejor este tema:</p>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1"></a><span class="kw">plot</span>(lr_Pts_<span class="dv">2014</span>)</span></code></pre></div>
<p><img src="index_files/figure-html/unnamed-chunk-21-1.png" width="672" /><img src="index_files/figure-html/unnamed-chunk-21-2.png" width="672" /><img src="index_files/figure-html/unnamed-chunk-21-3.png" width="672" /><img src="index_files/figure-html/unnamed-chunk-21-4.png" width="672" /></p>
<p><em>Residuals vs Fitted</em> nos permite entender si las variables tienen una relación lineal y verificar la dispersión. Tal como se mencionó arriba, nos encontramos frente a una concentración de residuos cuando eje <em>x</em> toma el valor 0 (cero).</p>
<p><em>Q-Q Plot</em> muestra la acumulación de residuos por quantiles, si la distribución es normal los residuos se encuentran cercanos a la recta y en casos contrarios la distribución no es normal. En este caso, la distribución tiende a ser normal, aunque con algunas desviaciones en los extremos. La única observación es que hay que prestar atención a las observaciones 12, 30 y 8 ya que podrían traernos problemas.</p>
<p><em>Scale-location</em> nos permite comprobar la homocedasticidad del modelo utilizando los residuos de forma estandarizada.La distribución es homocedástica, ya que podemos observar la línea roja tiende a ser plana por lo que asumimos que la varianza en los residuos no cambia en función de <em>x</em>.</p>
<p><em>Residuals vs Leverage </em> es clave en la detección de puntos con influencia en el cálculo de estimaciones de parámetros. Los puntos ubicados fuera de los límites de las líneas discontinuas deben ser analizados de manera individual para detectar anomalías. En este modelo no hay residuos que sobrepasen las lineas de distancia de Cook, es decir que no hay valores atípicos influyentes.</p>
</div>
<div id="residuos-rl-inversión_abs" class="section level3">
<h3><span class="header-section-number">4.2.2</span> Residuos RL inversión_abs</h3>
<p>Ahora, hacemos el análisis de los residuos de la regresión lineal simple con inversión absoluta.</p>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1"></a>residuos_inversionabs &lt;-<span class="st"> </span><span class="kw">residuals</span>(lr_inversion_absoluta)</span>
<span id="cb42-2"><a href="#cb42-2"></a></span>
<span id="cb42-3"><a href="#cb42-3"></a>residuos_inversionabs</span></code></pre></div>
<pre><code>##           1           2           3           4           5           6 
##  -2.1821682  -4.0664956   0.6901061 -10.0721386   3.9696634  -6.3573389 
##           7           8           9          10          11          12 
##   3.9335044  -9.3927310   3.7829510   3.5436618  -7.1424114  -9.6307419 
##          13          14          15          16          17          18 
##   4.6777975  23.5495605  14.9447904  12.9809495  10.3582277   4.7762854 
##          19          20          21          22          23          24 
##  -6.6756304  25.9152971   5.0319923  -8.3506733   1.0319923  -2.7528245 
##          25          26          27          28          29          30 
##  -4.5899625  -7.2760358  -7.8864488  -7.1016320  -3.5671347 -22.1424114</code></pre>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1"></a><span class="kw">ggplot</span>() <span class="op">+</span></span>
<span id="cb44-2"><a href="#cb44-2"></a><span class="st">  </span><span class="kw">geom_point</span>(<span class="kw">aes</span>(<span class="dt">x =</span> datos<span class="op">$</span>inversion_abs, <span class="dt">y =</span> residuos_inversionabs)) <span class="op">+</span></span>
<span id="cb44-3"><a href="#cb44-3"></a><span class="st">  </span><span class="kw">geom_hline</span>(<span class="dt">yintercept =</span> <span class="dv">0</span>, <span class="dt">col =</span> <span class="st">&#39;red&#39;</span>)  <span class="op">+</span></span>
<span id="cb44-4"><a href="#cb44-4"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">title=</span><span class="st">&quot;Residuos RL: Pts e inversion_abs&quot;</span>,</span>
<span id="cb44-5"><a href="#cb44-5"></a>       <span class="dt">y=</span><span class="st">&quot;residuos&quot;</span>,</span>
<span id="cb44-6"><a href="#cb44-6"></a>       <span class="dt">x=</span><span class="st">&quot;inversion_abs&quot;</span>) <span class="op">+</span></span>
<span id="cb44-7"><a href="#cb44-7"></a><span class="st">  </span><span class="kw">theme_minimal</span>() </span></code></pre></div>
<p><img src="index_files/figure-html/unnamed-chunk-23-1.png" width="672" /></p>
<p>Como se puede observar, hay cierta aleatoriedad en la distribución de los residuos mientras que el promedios de los residuos se aproxima a cero. Sin embargo, como el caso anterior podemos encontrar una concentración de residuos entre 0 y 2 del eje <em>x</em> y la mayoría de los puntos toman valores de entre 10 y -10 en el eje <em>y</em>. Vemos otros gráficos para entender mejor:</p>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1"></a><span class="kw">plot</span>(lr_inversion_absoluta)</span></code></pre></div>
<p><img src="index_files/figure-html/unnamed-chunk-24-1.png" width="672" /><img src="index_files/figure-html/unnamed-chunk-24-2.png" width="672" /><img src="index_files/figure-html/unnamed-chunk-24-3.png" width="672" /><img src="index_files/figure-html/unnamed-chunk-24-4.png" width="672" /></p>
<p><em>Residual vs Fitted</em> confirma una dispersión aleatoria de los residuos. No nos encontramos frente a ningún patrón considerable. <em>Scale-Location</em> también confirma la distribución aleatoria de los residuos, lo que nos permite aceptar el supuesto de homocedasticidad.</p>
<p><em>Q-Q Plot</em> muestra una distribución relativamente normal. Los valores 20 y 14 deberían ser considerados en casos futuros pero no son considerados valores extremos ni outliers por lo que podemos confirmar el supuesto de normalidad.</p>
<p>En <em>Residuals vs Leverage</em> el residuo 20 se encuentra cercano a la linea de Cook en el margen superior derecho. Aunque no pase las lineas, otra vez, esta podría ser una observación que impacte en el cálculo de estimación de parámetros.</p>
</div>
<div id="residuos-rl-valor" class="section level3">
<h3><span class="header-section-number">4.2.3</span> Residuos RL valor</h3>
<p>Ahora vamos a los residuos del modelo de regresión entre las variables <em>Pts</em> y <em>valor</em>.</p>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1"></a>residuos_valor &lt;-<span class="st"> </span><span class="kw">residuals</span>(lr_valor)</span>
<span id="cb46-2"><a href="#cb46-2"></a></span>
<span id="cb46-3"><a href="#cb46-3"></a>residuos_valor</span></code></pre></div>
<pre><code>##           1           2           3           4           5           6 
##   5.9339080  -0.7691283   8.3027111  -6.9594219  17.7293917  -2.5646121 
##           7           8           9          10          11          12 
##   6.9961974 -12.7593176   7.0128587   5.5562808  -3.3245391 -12.8127830 
##          13          14          15          16          17          18 
##   6.4218913   4.4257820  15.0984555   6.7288704  12.3240451  -0.6857655 
##          19          20          21          22          23          24 
## -11.5210133  13.5462094   6.6629509 -12.8123177   2.4851673  -1.7379836 
##          25          26          27          28          29          30 
##  -6.9550099  -6.5060086  -4.0668181  -2.0614194 -14.8804711 -18.8081104</code></pre>
<p>Graficamos:</p>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1"></a><span class="kw">ggplot</span>() <span class="op">+</span></span>
<span id="cb48-2"><a href="#cb48-2"></a><span class="st">  </span><span class="kw">geom_point</span>(<span class="kw">aes</span>(<span class="dt">x =</span> datos<span class="op">$</span>valor, <span class="dt">y =</span> residuos_valor)) <span class="op">+</span></span>
<span id="cb48-3"><a href="#cb48-3"></a><span class="st">  </span><span class="kw">geom_hline</span>(<span class="dt">yintercept =</span> <span class="dv">0</span>, <span class="dt">col =</span> <span class="st">&#39;red&#39;</span>)  <span class="op">+</span></span>
<span id="cb48-4"><a href="#cb48-4"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">title=</span><span class="st">&quot;Residuos RL: Pts y valor&quot;</span>,</span>
<span id="cb48-5"><a href="#cb48-5"></a>       <span class="dt">y=</span><span class="st">&quot;residuos&quot;</span>,</span>
<span id="cb48-6"><a href="#cb48-6"></a>       <span class="dt">x=</span><span class="st">&quot;valor&quot;</span>) <span class="op">+</span></span>
<span id="cb48-7"><a href="#cb48-7"></a><span class="st">  </span><span class="kw">theme_minimal</span>() </span></code></pre></div>
<p><img src="index_files/figure-html/unnamed-chunk-26-1.png" width="672" /></p>
<p>La distribución de puntos es similar tanto encima como debajo del 0 en el eje <em>y</em>. Gran parte de los puntos se concentran entre el 0 y el 20 en el eje <em>x</em>, por lo que la distribución no es pareja ya que unos pocos equipos tienen valores mayores a 30 millones de euros.</p>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1"></a><span class="kw">plot</span>(lr_valor)</span></code></pre></div>
<p><img src="index_files/figure-html/unnamed-chunk-27-1.png" width="672" /><img src="index_files/figure-html/unnamed-chunk-27-2.png" width="672" /><img src="index_files/figure-html/unnamed-chunk-27-3.png" width="672" /><img src="index_files/figure-html/unnamed-chunk-27-4.png" width="672" /></p>
<p><em>Residuals vs Fitted</em> muestra una concentración de residuos en la primera parte del gráfico, al igual que <em>Scale-Location</em> donde también notamos un patrón de concentración de residuos.</p>
<p><em>Q-Q Plot</em> muestra una distribución relativamente normal. El valor 5 debería ser considerado en casos futuros, pero no es considerado valor extremo ni outlier por lo que podemos confirmar el supuesto de normalidad.</p>
<p><em>Residuals vs Leverage</em> nos permite observar que ningun residuo pasa las líneas de Cook, aunque el punto 19 se encuentra muy próximo y si bien esta dentro de lo esperable podría ser un valor atípico influyente.</p>
<p>Luego de los análisis de residuos realizados hasta el momento, podemos concluir en que los residuos tienen una distribución un tanto desigual con concentraciones particulares y valores en algunos casos moderados/extremos. Vamos a trabajar con regresión lineal múltiple para analizar el caso desde otras perspectivas.</p>
</div>
</div>
<div id="rl-multiple" class="section level2">
<h2><span class="header-section-number">4.3</span> RL Multiple</h2>
<p>¿Por qué vamos a usar una regresión lineal múltiple? Ya que nos permite generar un modelo (lineal) en el que la variable dependiente <em>y</em> está determinada por un conjunto de variables independientes.</p>
<p>Vamos a calcular la regresión lineal múltiple con todas las variables independientes de que están disponibles en nuestro dataset y que se relacionan con la variavle Pts (puntos en el torneo 2015):</p>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1"></a>mlr_<span class="dv">0</span> &lt;-<span class="st">  </span><span class="kw">lm</span>(Pts <span class="op">~</span><span class="st"> </span>. ,</span>
<span id="cb50-2"><a href="#cb50-2"></a>               datos)</span>
<span id="cb50-3"><a href="#cb50-3"></a></span>
<span id="cb50-4"><a href="#cb50-4"></a>mlr_<span class="dv">0</span></span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Pts ~ ., data = datos)
## 
## Coefficients:
##        (Intercept)         Pts_2012_13         Pts_2013_14            Pts_2014  
##          15.058086           -0.084927            0.008748            0.575616  
##      inversion_abs  inversion_relativa               valor    libertadoresTRUE  
##          -2.173272           40.110542            0.834816            3.896544  
##   sudamericanaTRUE         ascensoTRUE  
##          -1.348871            7.400458</code></pre>
<p>Ahora vemos las estadísticas de resumen y los coeficientes:</p>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1"></a><span class="kw">summary</span>(mlr_<span class="dv">0</span>)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Pts ~ ., data = datos)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -12.1568  -3.9097  -0.2494   3.4886  15.7965 
## 
## Coefficients:
##                     Estimate Std. Error t value Pr(&gt;|t|)  
## (Intercept)        15.058086   7.459359   2.019   0.0571 .
## Pts_2012_13        -0.084927   0.103988  -0.817   0.4237  
## Pts_2013_14         0.008748   0.106711   0.082   0.9355  
## Pts_2014            0.575616   0.223596   2.574   0.0181 *
## inversion_abs      -2.173272   1.268791  -1.713   0.1022  
## inversion_relativa 40.110542  15.874772   2.527   0.0201 *
## valor               0.834816   0.338797   2.464   0.0229 *
## libertadoresTRUE    3.896544   5.391639   0.723   0.4782  
## sudamericanaTRUE   -1.348871   3.915157  -0.345   0.7340  
## ascensoTRUE         7.400458   5.703893   1.297   0.2092  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 7.973 on 20 degrees of freedom
## Multiple R-squared:  0.7028, Adjusted R-squared:  0.5691 
## F-statistic: 5.256 on 9 and 20 DF,  p-value: 0.0009804</code></pre>
<p>El <em>p-value</em> general del modelo es de <em>0.0009804</em>, por lo que podemos considerarlo signficativo. El coeficiente de <em>Adjusted R-squared</em> es de <em>0.5691</em>, mientras que el de <em>Multiple R-squared</em> es de <em>0.7028</em>.</p>
<p>Las variables más significativas, con un <em>p-value</em> menor a 0.05, son <em>Pts_2014</em>, <em>inversion_relativa</em> y <em>valor</em> por lo que vamos a calcular una regresión multiple con estas variables.</p>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1"></a>mlr_<span class="dv">1</span> &lt;-<span class="st"> </span><span class="kw">lm</span>(Pts <span class="op">~</span><span class="st"> </span>Pts_<span class="dv">2014</span> <span class="op">+</span><span class="st"> </span></span>
<span id="cb54-2"><a href="#cb54-2"></a><span class="st">              </span>inversion_relativa <span class="op">+</span><span class="st"> </span></span>
<span id="cb54-3"><a href="#cb54-3"></a><span class="st">              </span>valor,</span>
<span id="cb54-4"><a href="#cb54-4"></a>            datos)</span>
<span id="cb54-5"><a href="#cb54-5"></a>mlr_<span class="dv">1</span></span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Pts ~ Pts_2014 + inversion_relativa + valor, data = datos)
## 
## Coefficients:
##        (Intercept)            Pts_2014  inversion_relativa               valor  
##            24.7700              0.3347             15.3771              0.4702</code></pre>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1"></a><span class="kw">summary</span>(mlr_<span class="dv">1</span>)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Pts ~ Pts_2014 + inversion_relativa + valor, data = datos)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -13.8207  -3.7897   0.7116   4.2455  13.3679 
## 
## Coefficients:
##                    Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)         24.7700     2.8622   8.654 3.93e-09 ***
## Pts_2014             0.3347     0.1165   2.873  0.00800 ** 
## inversion_relativa  15.3771     5.7650   2.667  0.01298 *  
## valor                0.4702     0.1546   3.041  0.00533 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 7.971 on 26 degrees of freedom
## Multiple R-squared:  0.6139, Adjusted R-squared:  0.5694 
## F-statistic: 13.78 on 3 and 26 DF,  p-value: 1.419e-05</code></pre>
<p>A diferencia de la regresión multiple anterior, el coeficiente <em>Adjusted R-squared</em> aumenta levemente de 0.5691 <em>a 0.5694</em>. Por otro lado, el <em>Multiple R-squared</em> desciende de 0.7028 <em>a 0.6139</em>. El <em>p-value</em> es menor a 0.05, por lo que podemos aceptar el modelo ya que es significativo.</p>
<p>Si tomamos el <em>Adjusted R-squared</em>, podemos decir que este segundo modelo explica el <em>56.9%</em> de la variabilidad de la variable dependiente <em>y</em>, que este caso es la llamada <em>Pts</em>.</p>
</div>
<div id="residuos-rlm" class="section level2">
<h2><span class="header-section-number">4.4</span> Residuos RLM</h2>
<p>Vamos a enfocarnos en los residuos de la regresión lineal múltiple ajustada con tres variables. Graficamos:</p>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1"></a><span class="kw">plot</span>(mlr_<span class="dv">1</span>)</span></code></pre></div>
<p><img src="index_files/figure-html/unnamed-chunk-32-1.png" width="672" /><img src="index_files/figure-html/unnamed-chunk-32-2.png" width="672" /><img src="index_files/figure-html/unnamed-chunk-32-3.png" width="672" /><img src="index_files/figure-html/unnamed-chunk-32-4.png" width="672" /></p>
<p><em>Residuals vs Fitted</em> muestra cierta linealidad de las variables (aunque con una caída, un pozo y después una meseta) y una dispersión bastante homogenea de residuos. No hay quiebres que evidencien un patrón al que debamos prestarle atención. Sí debemos prestar atención al residuo 19, que ya ha sido mencionado, y el 12.</p>
<p><em>Scale-location</em> muestra la distribución de los reisduos a lo largo del rango de predictores y en el gráfico la distribución parece aleatoria aunque tiende a crecer exponencialmente hacia el final.</p>
<p>Como conclusión de los dos apartados anteriores podemos aceptar el supuesto de homocedasticidad.</p>
<p><em>Q-Q Plot</em> muestra una distribución normal de los residuos, con desviaciones a considerar en los ya mencionados residuos 12 y 19.</p>
<p><em>Residuals vs Leverage</em> arroja que ningún valor sobrepasa las lineas de Cook. Otra vez el valor 19 muestra diferencias del resto y deberíamos prestar más atención ya que podría ser una observación influyente y/o anormal.</p>
</div>
<div id="conclusiones" class="section level2">
<h2><span class="header-section-number">4.5</span> Conclusiones</h2>
<p>Hasta el momento trabajamos con distintos modelos de regresión y abordamos los residuos de los mismos para intentar entender qué variables pueden ayudarnos a predecir y comprender mejor los desempeños de los equipos de primera división del fútbol argentino en el torneo 2015. Encontramos correlación entre la variable <em>Pts</em> y las variables predictoras <em>Pts_2014</em>, <em>inversion_abs</em> y <em>valor</em> que arrojaron los valores más altos del coeficiente de correlación de Pearson.</p>
<p>Los coeficientes de las regresiones lineales simples indican que la relación entre <em>Pts</em> y <em>valor</em> es la más solida, el R cuadrado ajustado es de <em>0.359</em>, esto significa que la variable <em>valor</em> explica el <em>35.9%</em> de la variabilidad de los puntos obtenidos en el torneo 2015, es decir nuestra variable <em>Pts</em>.</p>
<p>La regresión entre <em>Pts</em> y <em>Pts_2014</em> arrojó un valor de R cuadrado ajustado de <em>0.3019</em>, mientras que en la regresión entre <em>Pts</em> e <em>inversion_abs</em> el R cuadrado ajustado fue de <em>0.2589</em>.</p>
<p>En cuanto a regresiones lineales múltiples, en la primera se trabajó con todas las variables predictoras del data set, mientras que en el segundo caso seleccionamos las tres variables de mayor significancia según su p-value: <em>Pts_2014</em>, <em>inversion_relativa</em> y <em>valor</em>. El valor del multiple R-squared fue <em>0.7028</em> al trabajar con todas las variables y <em>0.6139</em> para el caso en el que solo trabajamos con las seleccionadas. Por otro lado, casi no hubo diferencia en el valor de adjusted R-squared, donde fueron <em>0.5691</em> y <em>0.5694</em> respectivamente.</p>
<p>La regresión multiple con las variables seleccionadas arrojó un coeficiente de determinación mayor, y que explica que el <em>56.94%</em> de la variabilidad de la variable <em>Pts</em>.</p>
<p>Al ver los residuos, nos encontramos con que gráficos muestran que en líneas generales estos tienen una distribución aleatoria, que tienden a ser normales y cumplen los principios de linealidad y homocedasticidad. Sí hay valores particulares a los que deberíamos prestar atención, como por ejemplo 19 (en mayor medida), 12, 20 y 30.</p>
<p>Si bien pueden servir como orientación, estos modelos no tienen un caracter predictivo determinante ya que la linealiad no es absoluta y nuestros modelos tampoco. La predicciones pueden ayudarnos a formar un nuevo paradigma de comprensión y predicción aproximado y matemático que vaya más allá de la suposición a la que el deporte acostumbra. Pero, en el fútbol intervienen muchísimos factores que exceden los que conforman nuestro data set y que agotan también la capacidad de estos modelos (simples y múltiples) de regresión lineal.</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>


    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
